---
ddns:
  configs:
    home_ipv4:
      name: openwrt.home
      service_name: cloudflare.com
      use_https: 1
      lookup_host: '{{ fqdn }}'
      domain: '{{ fqdn }}'
      username: '{{ vault_cloudflare_user }}'
      password: '{{ vault_cloudflare_pass }}'
      interface: wan
      ip_source: network
      ip_network: wan
      use_ipv6: 0
      cacert: '/etc/ssl/certs'
      enabled: 1
    home_ipv6:
      name: openwrt.home
      service_name: cloudflare.com
      use_https: 1
      lookup_host: '{{ fqdn }}'
      domain: '{{ fqdn }}'
      username: '{{ vault_cloudflare_user }}'
      password: '{{ vault_cloudflare_pass }}'
      interface: wan6
      ip_source: network6
      ip_network: wan6
      use_ipv6: 1
      cacert: '/etc/ssl/certs'
      enabled: 1
dhcp:
  global:
    local: '/{{ domain }}/'
    domain: '{{ domain }}'
  dhcp_instances:
    guest:
      interface: guest
      start: 50
      limit: 100
      leasetime: 1h
  hosts:
    - name: diltram
      mac: '64:76:ba:b1:99:0e'
      ip: '192.168.1.10'
    - name: monitoring
      mac: '6e:1b:6b:0e:6b:69'
      ip: '192.168.1.3'
    - name: apple-tv
      mac: 'd0:03:4b:3a:80:9b'
      ip: '192.168.1.11'
