---
- name: configure global config
  uci: command=set key='ddns.global.{{ item.key }}' value='{{ item.value }}'
  with_dict:
    '{{ ddns.global }}'
  notify:
    - ddns reload
    - uci commit

- name: configure required services
  uci: command=set key='ddns.{{ item.key }}' value=service
  with_dict:
    '{{ ddns.configs }}'
  notify:
    - ddns reload
    - uci commit

- name: configure ddns services
  include_role: 
    name: utils
    tasks_from: loop_over_config
  with_dict:
    '{{ ddns.configs }}'
  loop_control:
    loop_var: config
  vars:
    key: ddns
  notify:
    - ddns reload
    - uci commit
